version: '3.7'

services:
  frontend:
    container_name: ccac-frontend
    build:
      context: .
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/usr/share/nginx/html/certbot
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-ccac-backend}
      BACKEND_PORT: ${BACKEND_PORT:-80}
      NGINX_CERT_FILE: /run/secrets/nginx_cert
      NGINX_KEY_FILE: /run/secrets/nginx_key
    networks:
      - ccac_bridge_network
    secrets:
      - nginx_cert
      - nginx_key
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/usr/share/nginx/html/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

secrets:
  nginx_cert:
    file: ${NGINX_PUBLIC_FILE:-/etc/nginx/tls/certs/nginx-ccac-selfsigned.crt}
  nginx_key:
    file: ${NGINX_PRIVATE_FILE:-/etc/nginx/tls/certs/nginx-ccac-selfsigned.key}

networks:
  ccac_bridge_network:
    name: ${CCAC_BRIDGE_NETWORK:-ccac-go_bridge-net}
    external: true
